### ISSUE TITLE
HTMLText flickering when changing wordWrapWidth frequently in pixi.js-legacy with forceCanvas: true

### ISSUE THREAD

**Issue by RhapsodY-69** [pixijs/html-text#41] opened 2023-02-15 21:55 UTC
Here is working example of an issue https://jsfiddle.net/Rhapsody6969/zdkpfbqL/12/

**Comment by bigtimebuddy** [comment] 2023-02-16 16:25
This is not a bug.

It's important to understand some of the differences with HTMLText vs Text. HTMLText rendering is _asynchronous_ and Text rendering is _synchronous_. So if the interval you're trying to render is _faster_ then the time required by your Browser to show, so it's going to flicker. Try changing your setInterval to 100ms instead of 16.6ms. Notice no flicker.

HTMLText is not designed to be set 60 fps. If you do that it's going to be a huge performance killer for your application. Text is the same way, but we just don't see a flicker. If you need fast text use BitmapText.

If for some reason you need to set repeatedly change style, you'll need to debounce updates. You can do that by waiting for `htmlText.texture.baseTexture.on('update', () => {})` after you change the style or text. This will let you know when it's ready to render.

**Comment by RhapsodY-69** [comment] 2023-02-17 14:39
@bigtimebuddy Thank you for your reply. I have two more questions and I would be very grateful if you would answer them too.

I have discovered new important details of my issue. It's flickering even with setInterval 100ms, but if we use **pixi.js-legacy**, and **forceCanvas: true**.
Here is example once again https://jsfiddle.net/Rhapsody6969/zdkpfbqL/20/
**So the first question is**: do you know how can I use HTMLText with it? I cannot switch my app to webGL

**And the second**: may be you can explain me what specifically is asynchronous there in your code, so I can fork and edit it, please? I found that there is asynchronous code in updateText function – bugfix for safari fonts loading, however I do not need my app to support Safari browser

**Comment by bigtimebuddy** [comment] 2023-02-17 16:36
I can look into the flicker on canvas renderer. I have some ideas why that might be the case. 

The reason this is async is because of how it renders. Basically, we create an SVG for the text as a string, convert that into an HTMLImageElement, and then draw it to the canvas. In order to draw it, the image needs to load `onload`. All that happens here:

https://github.com/pixijs/html-text/blob/2b3ca2aa7e5795fff2343ee29eda0d3153d5816f/src/HTMLText.ts#L202-L211

That's definitely a technical trade-off with this technique.

**Comment by RhapsodY-69** [comment] 2023-02-20 09:02
@bigtimebuddy Yes, can you check canvas renderer flicker, please?

**Comment by galkinrost** [comment] 2023-02-21 08:28
Hi, everyone! 
Actually we also faced the flickering issue using canvas renderer. 
@bigtimebuddy do you think there is any chance it'll be fixed in the near feature? It's actually a blocker for us to start using html-text, so sorry to bother you 😅

**Comment by bigtimebuddy** [comment] 2023-02-21 14:07
I think I have a good idea how to solve this by using two images to ping-ping render. That would avoid the times the image is loading (and showing nothing).

**Closed as completed** 2023-02-21 16:50 UTC
